In [15]:
#to check whether number is prime
b = int(input())
f=0
for i in range(2,b):
  if b%i == 0:
    f = f + 1;
if f == 0:
  print("prime")
else:
  print("not prime")


33
not prime


In [26]:
#fibonacci sequence
'''
def fibo(n):
  a = 0
  b = 1
  if n == 1:
    print(a)
  else:
    print(a)
    print(b)
    for i in range(2,n):
      c = a + b
      a = b
      b = c
      print(c)
'''
def fibo(n):
  if n ==1:
    return 0
  elif n == 2:
    return 1
  else:
    return fibo(n-1) + fibo(n-2)
a = int(input())
fibo(a)

10


34

In [29]:
#lcm and gcd
a = int(input())
b = int(input())
def gcd(a,b):
  l=0
  for i in range(1,min(a,b)+1):
    if a%i == 0 and b%i == 0:
      l = i
  return l
print(gcd(a,b))
l = gcd(a,b)
lcm = (a*b)/l
print(int(lcm))

4
2
2
4


In [32]:
#calculator
a=int(input())
b=int(input())
print("enter option 1 for add 2 for sub 3 for mul 4 for div")
c=int(input())
def add(a,b):
  return a+b
def sub(a,b):
  return a-b
def mul(a,b):
  return a*b
def div(a,b):
  return a/b
if c==1:
  print(add(a,b))
elif c==2:
  print(sub(a,b))
elif c==3:
  print(mul(a,b))
elif c==4:
  print(div(a,b))
else:
  print("invalid option")

4
3
enter option 1 for add 2 for sub 3 for mul 4 for div
1
7


In [38]:
# output without duplicates
list = input().split()
set1= set(list)
print(set1)

1 2 3 2 1
{'2', '1', '3'}


In [51]:
from os import name
#create dictionary
thisdict = {
      "name":"amulya",
      "age":18,
      "gender":"female",
      "phone":9000353549,
      "email":"xyz"
  }
print(thisdict)

{'name': 'amulya', 'age': 18, 'gender': 'female', 'phone': 9000353549, 'email': 'xyz'}


In [52]:
#matrix operations
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("matrix-1:\n",a)
print("matrix-2:\n",b)
result1 = np.add(a,b)
result2 = np.dot(a,b)
print("addition:\n",result1)
print("multiplication:\n",result2)

matrix-1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix-2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
addition:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
multiplication:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [ ]:
m

In [69]:
from itertools import count
#find common word
import numpy as np
a=input("text: ")
count = np.zeros(len(a))
word= a.split()
for i in range(len(word)):
  for j in range(i+1,len(word)):
    if word[i]==word[j]:
      count[i]=count[i]+1
large = 0
for i in range(0,len(word)):
  if count[i]>count[large]:
    large = i
print(word[large])




text: nice nice god job
nice


In [74]:
import random
import string
#random password
l=int(input("number of characters in password: "))
random_string = ''.join(random.choice(string.ascii_letters) for i in range(l))
print(random_string)




number of characters in password: 4
USMz
